/* GENERATED by tools/tune.py - do not edit. */
/* Test scaffolding only. Not compiled into the watchface. */

#pragma once
#include <stdint.h>

#define RESOURCE_ID_W_ONE 1
#define RESOURCE_ID_W_TWO 2
#define RESOURCE_ID_W_THREE 3
#define RESOURCE_ID_W_FOUR 4
#define RESOURCE_ID_W_FIVE 5
#define RESOURCE_ID_W_SIX 6
#define RESOURCE_ID_W_SEVEN 7
#define RESOURCE_ID_W_EIGHT 8
#define RESOURCE_ID_W_NINE 9
#define RESOURCE_ID_W_TEN 10
#define RESOURCE_ID_W_ELEVEN 11
#define RESOURCE_ID_W_TWELVE 12
#define RESOURCE_ID_W_THIRTEEN 13
#define RESOURCE_ID_W_FOURTEEN 14
#define RESOURCE_ID_W_FIFTEEN 15
#define RESOURCE_ID_W_SIXTEEN 16
#define RESOURCE_ID_W_SEVENTEEN 17
#define RESOURCE_ID_W_EIGHTEEN 18
#define RESOURCE_ID_W_NINETEEN 19
#define RESOURCE_ID_W_TWENTY 20
#define RESOURCE_ID_W_TWENTYDASH 21
#define RESOURCE_ID_W_QUARTER 22
#define RESOURCE_ID_W_HALF 23
#define RESOURCE_ID_W_PAST 24
#define RESOURCE_ID_W_TO 25
#define RESOURCE_ID_W_MIDNIGHT 26
#define RESOURCE_ID_W_MIDDAY 27
#define RESOURCE_ID_W_NOON 28
#define RESOURCE_ID_W_MINUTE 29
#define RESOURCE_ID_W_MINUTES 30
#define RESOURCE_ID_W_SOLO_MIDNIGHT 31
#define RESOURCE_ID_W_SOLO_MIDDAY 32
#define RESOURCE_ID_W_D0 33
#define RESOURCE_ID_W_D1 34
#define RESOURCE_ID_W_D2 35
#define RESOURCE_ID_W_D3 36
#define RESOURCE_ID_W_D4 37
#define RESOURCE_ID_W_D5 38
#define RESOURCE_ID_W_D6 39
#define RESOURCE_ID_W_D7 40
#define RESOURCE_ID_W_D8 41
#define RESOURCE_ID_W_D9 42
#define RESOURCE_ID_W_MON1 43
#define RESOURCE_ID_W_MON2 44
#define RESOURCE_ID_W_MON3 45
#define RESOURCE_ID_W_MON4 46
#define RESOURCE_ID_W_MON5 47
#define RESOURCE_ID_W_MON6 48
#define RESOURCE_ID_W_MON7 49
#define RESOURCE_ID_W_MON8 50
#define RESOURCE_ID_W_MON9 51
#define RESOURCE_ID_W_MON10 52
#define RESOURCE_ID_W_MON11 53
#define RESOURCE_ID_W_MON12 54
#define RESOURCE_ID_W_ST 55
#define RESOURCE_ID_W_ND 56
#define RESOURCE_ID_W_RD 57
#define RESOURCE_ID_W_TH 58
#define RESOURCE_ID_W_DOW_SUN 59
#define RESOURCE_ID_W_DOW_MON 60
#define RESOURCE_ID_W_DOW_TUE 61
#define RESOURCE_ID_W_DOW_WED 62
#define RESOURCE_ID_W_DOW_THU 63
#define RESOURCE_ID_W_DOW_FRI 64
#define RESOURCE_ID_W_DOW_SAT 65
#define RESOURCE_ID_W_SOLO_ONE 66
#define RESOURCE_ID_W_SOLO_TWO 67
#define RESOURCE_ID_W_SOLO_THREE 68
#define RESOURCE_ID_W_SOLO_FOUR 69
#define RESOURCE_ID_W_SOLO_FIVE 70
#define RESOURCE_ID_W_SOLO_SIX 71
#define RESOURCE_ID_W_SOLO_SEVEN 72
#define RESOURCE_ID_W_SOLO_EIGHT 73
#define RESOURCE_ID_W_SOLO_NINE 74
#define RESOURCE_ID_W_SOLO_TEN 75
#define RESOURCE_ID_W_SOLO_ELEVEN 76
#define RESOURCE_ID_W_SOLO_OCLOCK 77
#define RESOURCE_ID_W_SOLO_THE 78
#define RESOURCE_ID_W_SOLO_WITCHING 79
#define RESOURCE_ID_W_SOLO_HOUR 80
#define RESOURCE_ID_W_TWENTYFIVE 81
#define RESOURCE_ID_W_JUST_GONE 82
#define RESOURCE_ID_W_NEARLY 83
#define RESOURCE_ID_H_FOUR 84
#define RESOURCE_ID_H_FIVE 85
#define RESOURCE_ID_H_EIGHT 86
#define RESOURCE_ID_H_ELEVEN 87
#define RESOURCE_ID_H_FOURTEEN 88
#define RESOURCE_ID_H_FIFTEEN 89
#define RESOURCE_ID_H_EIGHTEEN 90
#define RESOURCE_ID_H_HALF 91

typedef struct { uint8_t asc, desc; } WordInk;

/* Ink above and below the baseline, per word and per typeface.
   The shipping WORDS[] carries the family BOX, which is routinely
   taller than the letters in it, so bounds-checking against that
   would pass anything. This is what is really visible - and the
   handwriting's extents are its own, measured off the drawn page. */
/* Not TYPEFACE_COUNT: this header is included BEFORE
   geometry.h, so the number is repeated and then asserted
   equal in harness.c, which sees both. */
#define GENERATED_TYPEFACES 2
static const WordInk WORD_INK[GENERATED_TYPEFACES][83] = {
  {
    {18, 0},        /* one */
    {26, 0},        /* two */
    {32, 1},        /* three */
    {34, 12},        /* four */
    {34, 12},        /* five */
    {23, 1},        /* six */
    {18, 0},        /* seven */
    {32, 17},        /* eight */
    {23, 0},        /* nine */
    {26, 0},        /* ten */
    {34, 1},        /* eleven */
    {34, 1},        /* twelve */
    {32, 1},        /* thirteen */
    {34, 12},        /* fourteen */
    {34, 12},        /* fifteen */
    {26, 1},        /* sixteen */
    {26, 0},        /* seventeen */
    {32, 17},        /* eighteen */
    {26, 0},        /* nineteen */
    {26, 16},        /* twenty */
    {26, 16},        /* twenty- */
    {26, 15},        /* quarter */
    {34, 12},        /* half */
    {26, 15},        /* past */
    {26, 0},        /* to */
    {33, 17},        /* midnight */
    {33, 16},        /* midday */
    {18, 0},        /* noon */
    {16, 0},        /* minute */
    {16, 0},        /* minutes */
    {37, 19},        /* midnight */
    {37, 18},        /* midday */
    {12, 0},        /* 0 */
    {12, 0},        /* 1 */
    {12, 0},        /* 2 */
    {12, 0},        /* 3 */
    {12, 0},        /* 4 */
    {12, 0},        /* 5 */
    {12, 0},        /* 6 */
    {12, 0},        /* 7 */
    {12, 0},        /* 8 */
    {12, 0},        /* 9 */
    {15, 8},        /* Jan. */
    {17, 3},        /* Feb. */
    {15, 4},        /* Mar. */
    {17, 8},        /* Apr. */
    {15, 9},        /* May */
    {15, 8},        /* Jun. */
    {19, 8},        /* Jul. */
    {17, 9},        /* Aug. */
    {15, 8},        /* Sep. */
    {16, 0},        /* Oct. */
    {16, 1},        /* Nov. */
    {16, 0},        /* Dec. */
    {9, 0},         /* st */
    {11, 0},        /* nd */
    {11, 0},        /* rd */
    {11, 0},        /* th */
    {15, 5},        /* Sun. */
    {15, 4},        /* Mon. */
    {15, 0},        /* Tue. */
    {18, 0},        /* Wed. */
    {17, 1},        /* Thu. */
    {15, 3},        /* Fri. */
    {15, 5},        /* Sat. */
    {20, 1},        /* one */
    {29, 0},        /* two */
    {36, 1},        /* three */
    {39, 13},        /* four */
    {39, 13},        /* five */
    {27, 1},        /* six */
    {20, 0},        /* seven */
    {36, 19},        /* eight */
    {27, 0},        /* nine */
    {29, 0},        /* ten */
    {39, 1},        /* eleven */
    {39, 1},        /* o'|clock */
    {36, 1},        /* the */
    {36, 19},        /* witching */
    {36, 1},        /* hour */
    {34, 16},        /* twenty-five */
    {18, 11},        /* just|gone */
    {21, 10},        /* nearly */
  },
  {
    {18, 0},        /* one */
    {26, 0},        /* two */
    {32, 1},        /* three */
    {34, 15},        /* four        drawn */
    {34, 15},        /* five        drawn */
    {23, 1},        /* six */
    {18, 0},        /* seven */
    {34, 17},        /* eight       drawn */
    {23, 0},        /* nine */
    {26, 0},        /* ten */
    {34, 1},        /* eleven      drawn */
    {34, 1},        /* twelve */
    {32, 1},        /* thirteen */
    {34, 16},        /* fourteen    drawn */
    {34, 16},        /* fifteen     drawn */
    {26, 1},        /* sixteen */
    {26, 0},        /* seventeen */
    {34, 17},        /* eighteen    drawn */
    {26, 0},        /* nineteen */
    {26, 16},        /* twenty */
    {26, 16},        /* twenty- */
    {26, 15},        /* quarter */
    {34, 15},        /* half        drawn */
    {26, 15},        /* past */
    {26, 0},        /* to */
    {33, 17},        /* midnight */
    {33, 16},        /* midday */
    {18, 0},        /* noon */
    {16, 0},        /* minute */
    {16, 0},        /* minutes */
    {37, 19},        /* midnight */
    {37, 18},        /* midday */
    {12, 0},        /* 0 */
    {12, 0},        /* 1 */
    {12, 0},        /* 2 */
    {12, 0},        /* 3 */
    {12, 0},        /* 4 */
    {12, 0},        /* 5 */
    {12, 0},        /* 6 */
    {12, 0},        /* 7 */
    {12, 0},        /* 8 */
    {12, 0},        /* 9 */
    {15, 8},        /* Jan. */
    {17, 3},        /* Feb. */
    {15, 4},        /* Mar. */
    {17, 8},        /* Apr. */
    {15, 9},        /* May */
    {15, 8},        /* Jun. */
    {19, 8},        /* Jul. */
    {17, 9},        /* Aug. */
    {15, 8},        /* Sep. */
    {16, 0},        /* Oct. */
    {16, 1},        /* Nov. */
    {16, 0},        /* Dec. */
    {9, 0},         /* st */
    {11, 0},        /* nd */
    {11, 0},        /* rd */
    {11, 0},        /* th */
    {15, 5},        /* Sun. */
    {15, 4},        /* Mon. */
    {15, 0},        /* Tue. */
    {18, 0},        /* Wed. */
    {17, 1},        /* Thu. */
    {15, 3},        /* Fri. */
    {15, 5},        /* Sat. */
    {20, 1},        /* one */
    {29, 0},        /* two */
    {36, 1},        /* three */
    {39, 13},        /* four */
    {39, 13},        /* five */
    {27, 1},        /* six */
    {20, 0},        /* seven */
    {36, 19},        /* eight */
    {27, 0},        /* nine */
    {29, 0},        /* ten */
    {39, 1},        /* eleven */
    {39, 1},        /* o'|clock */
    {36, 1},        /* the */
    {36, 19},        /* witching */
    {36, 1},        /* hour */
    {34, 16},        /* twenty-five */
    {18, 11},        /* just|gone */
    {21, 10},        /* nearly */
  },
};

/* Has this word been drawn by hand? Independent of WORDS[]. */
static const uint8_t WORD_DRAWN[] = {
  0,   /* one */
  0,   /* two */
  0,   /* three */
  1,   /* four */
  1,   /* five */
  0,   /* six */
  0,   /* seven */
  1,   /* eight */
  0,   /* nine */
  0,   /* ten */
  1,   /* eleven */
  0,   /* twelve */
  0,   /* thirteen */
  1,   /* fourteen */
  1,   /* fifteen */
  0,   /* sixteen */
  0,   /* seventeen */
  1,   /* eighteen */
  0,   /* nineteen */
  0,   /* twenty */
  0,   /* twenty- */
  0,   /* quarter */
  1,   /* half */
  0,   /* past */
  0,   /* to */
  0,   /* midnight */
  0,   /* midday */
  0,   /* noon */
  0,   /* minute */
  0,   /* minutes */
  0,   /* midnight */
  0,   /* midday */
  0,   /* 0 */
  0,   /* 1 */
  0,   /* 2 */
  0,   /* 3 */
  0,   /* 4 */
  0,   /* 5 */
  0,   /* 6 */
  0,   /* 7 */
  0,   /* 8 */
  0,   /* 9 */
  0,   /* Jan. */
  0,   /* Feb. */
  0,   /* Mar. */
  0,   /* Apr. */
  0,   /* May */
  0,   /* Jun. */
  0,   /* Jul. */
  0,   /* Aug. */
  0,   /* Sep. */
  0,   /* Oct. */
  0,   /* Nov. */
  0,   /* Dec. */
  0,   /* st */
  0,   /* nd */
  0,   /* rd */
  0,   /* th */
  0,   /* Sun. */
  0,   /* Mon. */
  0,   /* Tue. */
  0,   /* Wed. */
  0,   /* Thu. */
  0,   /* Fri. */
  0,   /* Sat. */
  0,   /* one */
  0,   /* two */
  0,   /* three */
  0,   /* four */
  0,   /* five */
  0,   /* six */
  0,   /* seven */
  0,   /* eight */
  0,   /* nine */
  0,   /* ten */
  0,   /* eleven */
  0,   /* o'|clock */
  0,   /* the */
  0,   /* witching */
  0,   /* hour */
  0,   /* twenty-five */
  0,   /* just|gone */
  0,   /* nearly */
};

/* x-height of each word's family - the lowercase body height.
   Shared by both typefaces: the drawing template's mean line IS
   this number, so anything drawn to it matches by construction. */
static const uint8_t WORD_XHEIGHT[] = {
  18,   /* TIME      one */
  18,   /* TIME      two */
  18,   /* TIME      three */
  18,   /* TIME      four */
  18,   /* TIME      five */
  18,   /* TIME      six */
  18,   /* TIME      seven */
  18,   /* TIME      eight */
  18,   /* TIME      nine */
  18,   /* TIME      ten */
  18,   /* TIME      eleven */
  18,   /* TIME      twelve */
  18,   /* TIME      thirteen */
  18,   /* TIME      fourteen */
  18,   /* TIME      fifteen */
  18,   /* TIME      sixteen */
  18,   /* TIME      seventeen */
  18,   /* TIME      eighteen */
  18,   /* TIME      nineteen */
  18,   /* TIME      twenty */
  18,   /* TIME      twenty- */
  18,   /* TIME      quarter */
  18,   /* TIME      half */
  18,   /* TIME      past */
  18,   /* TIME      to */
  18,   /* TIME      midnight */
  18,   /* TIME      midday */
  18,   /* TIME      noon */
  11,   /* MINS      minute */
  11,   /* MINS      minutes */
  21,   /* SOLO      midnight */
  21,   /* SOLO      midday */
  10,   /* DATE      0 */
  10,   /* DATE      1 */
  10,   /* DATE      2 */
  10,   /* DATE      3 */
  10,   /* DATE      4 */
  10,   /* DATE      5 */
  10,   /* DATE      6 */
  10,   /* DATE      7 */
  10,   /* DATE      8 */
  10,   /* DATE      9 */
  10,   /* DATE      Jan. */
  10,   /* DATE      Feb. */
  10,   /* DATE      Mar. */
  10,   /* DATE      Apr. */
  10,   /* DATE      May */
  10,   /* DATE      Jun. */
  10,   /* DATE      Jul. */
  10,   /* DATE      Aug. */
  10,   /* DATE      Sep. */
  10,   /* DATE      Oct. */
  10,   /* DATE      Nov. */
  10,   /* DATE      Dec. */
  6,   /* ORD       st */
  6,   /* ORD       nd */
  6,   /* ORD       rd */
  6,   /* ORD       th */
  10,   /* DATE      Sun. */
  10,   /* DATE      Mon. */
  10,   /* DATE      Tue. */
  10,   /* DATE      Wed. */
  10,   /* DATE      Thu. */
  10,   /* DATE      Fri. */
  10,   /* DATE      Sat. */
  21,   /* SOLO      one */
  21,   /* SOLO      two */
  21,   /* SOLO      three */
  21,   /* SOLO      four */
  21,   /* SOLO      five */
  21,   /* SOLO      six */
  21,   /* SOLO      seven */
  21,   /* SOLO      eight */
  21,   /* SOLO      nine */
  21,   /* SOLO      ten */
  21,   /* SOLO      eleven */
  21,   /* SOLO      o'|clock */
  21,   /* SOLO      the */
  21,   /* SOLO      witching */
  21,   /* SOLO      hour */
  18,   /* TIME      twenty-five */
  11,   /* HEDGE     just|gone */
  11,   /* HEDGE     nearly */
};
