/* GENERATED by tools/tune.py - do not edit. */
/* Test scaffolding only. Not compiled into the watchface. */

#pragma once
#include <stdint.h>

#define RESOURCE_ID_W_ONE 1
#define RESOURCE_ID_W_TWO 2
#define RESOURCE_ID_W_THREE 3
#define RESOURCE_ID_W_FOUR 4
#define RESOURCE_ID_W_FIVE 5
#define RESOURCE_ID_W_SIX 6
#define RESOURCE_ID_W_SEVEN 7
#define RESOURCE_ID_W_EIGHT 8
#define RESOURCE_ID_W_NINE 9
#define RESOURCE_ID_W_TEN 10
#define RESOURCE_ID_W_ELEVEN 11
#define RESOURCE_ID_W_TWELVE 12
#define RESOURCE_ID_W_THIRTEEN 13
#define RESOURCE_ID_W_FOURTEEN 14
#define RESOURCE_ID_W_FIFTEEN 15
#define RESOURCE_ID_W_SIXTEEN 16
#define RESOURCE_ID_W_SEVENTEEN 17
#define RESOURCE_ID_W_EIGHTEEN 18
#define RESOURCE_ID_W_NINETEEN 19
#define RESOURCE_ID_W_TWENTY 20
#define RESOURCE_ID_W_TWENTYDASH 21
#define RESOURCE_ID_W_QUARTER 22
#define RESOURCE_ID_W_HALF 23
#define RESOURCE_ID_W_PAST 24
#define RESOURCE_ID_W_TO 25
#define RESOURCE_ID_W_MIDNIGHT 26
#define RESOURCE_ID_W_MIDDAY 27
#define RESOURCE_ID_W_NOON 28
#define RESOURCE_ID_W_THE 29
#define RESOURCE_ID_W_WITCHING 30
#define RESOURCE_ID_W_HOUR 31
#define RESOURCE_ID_W_OCLOCK 32
#define RESOURCE_ID_W_MINUTE 33
#define RESOURCE_ID_W_MINUTES 34
#define RESOURCE_ID_W_SOLO_MIDNIGHT 35
#define RESOURCE_ID_W_SOLO_MIDDAY 36
#define RESOURCE_ID_W_D0 37
#define RESOURCE_ID_W_D1 38
#define RESOURCE_ID_W_D2 39
#define RESOURCE_ID_W_D3 40
#define RESOURCE_ID_W_D4 41
#define RESOURCE_ID_W_D5 42
#define RESOURCE_ID_W_D6 43
#define RESOURCE_ID_W_D7 44
#define RESOURCE_ID_W_D8 45
#define RESOURCE_ID_W_D9 46
#define RESOURCE_ID_W_MON1 47
#define RESOURCE_ID_W_MON2 48
#define RESOURCE_ID_W_MON3 49
#define RESOURCE_ID_W_MON4 50
#define RESOURCE_ID_W_MON5 51
#define RESOURCE_ID_W_MON6 52
#define RESOURCE_ID_W_MON7 53
#define RESOURCE_ID_W_MON8 54
#define RESOURCE_ID_W_MON9 55
#define RESOURCE_ID_W_MON10 56
#define RESOURCE_ID_W_MON11 57
#define RESOURCE_ID_W_MON12 58
#define RESOURCE_ID_W_ST 59
#define RESOURCE_ID_W_ND 60
#define RESOURCE_ID_W_RD 61
#define RESOURCE_ID_W_TH 62

typedef struct { uint8_t asc, desc; } WordInk;

/* Ink above and below the baseline, per word. */
static const WordInk WORD_INK[] = {
  {16, 0},        /* one */
  {23, 0},        /* two */
  {29, 1},        /* three */
  {31, 11},        /* four */
  {31, 11},        /* five */
  {21, 1},        /* six */
  {16, 0},        /* seven */
  {29, 16},        /* eight */
  {21, 0},        /* nine */
  {23, 0},        /* ten */
  {31, 1},        /* eleven */
  {31, 1},        /* twelve */
  {29, 1},        /* thirteen */
  {31, 11},        /* fourteen */
  {31, 11},        /* fifteen */
  {23, 1},        /* sixteen */
  {23, 0},        /* seventeen */
  {29, 16},        /* eighteen */
  {23, 0},        /* nineteen */
  {23, 15},        /* twenty */
  {23, 15},        /* twenty- */
  {23, 14},        /* quarter */
  {31, 11},        /* half */
  {23, 14},        /* past */
  {23, 0},        /* to */
  {30, 16},        /* midnight */
  {30, 15},        /* midday */
  {16, 0},        /* noon */
  {29, 1},        /* the */
  {29, 16},        /* witching */
  {29, 1},        /* hour */
  {31, 1},        /* o'|clock */
  {15, 0},        /* minute */
  {15, 0},        /* minutes */
  {34, 18},        /* midnight */
  {34, 17},        /* midday */
  {12, 0},        /* 0 */
  {12, 0},        /* 1 */
  {12, 0},        /* 2 */
  {12, 0},        /* 3 */
  {12, 0},        /* 4 */
  {12, 0},        /* 5 */
  {12, 0},        /* 6 */
  {12, 0},        /* 7 */
  {12, 0},        /* 8 */
  {12, 0},        /* 9 */
  {15, 8},        /* Jan. */
  {17, 3},        /* Feb. */
  {15, 4},        /* Mar. */
  {17, 8},        /* Apr. */
  {15, 9},        /* May */
  {15, 8},        /* Jun. */
  {19, 8},        /* Jul. */
  {17, 9},        /* Aug. */
  {15, 8},        /* Sep. */
  {16, 0},        /* Oct. */
  {16, 1},        /* Nov. */
  {16, 0},        /* Dec. */
  {9, 0},         /* st */
  {11, 0},        /* nd */
  {11, 0},        /* rd */
  {11, 0},        /* th */
};
