/* GENERATED by tools/tune.py - do not edit. */
/* Canvases are tight around the ink; the layout stacks them with */
/* a constant gap, so padding a PNG opens that row's spacing. */

#pragma once
#include <stdint.h>

typedef struct {
  uint32_t res;   /* resource id            */
  uint8_t w, h;   /* canvas size in pixels  */
  uint8_t base;   /* canvas top -> baseline */
} WordGeom;

typedef enum {
  W_ONE,             /* one */
  W_TWO,             /* two */
  W_THREE,           /* three */
  W_FOUR,            /* four */
  W_FIVE,            /* five */
  W_SIX,             /* six */
  W_SEVEN,           /* seven */
  W_EIGHT,           /* eight */
  W_NINE,            /* nine */
  W_TEN,             /* ten */
  W_ELEVEN,          /* eleven */
  W_TWELVE,          /* twelve */
  W_THIRTEEN,        /* thirteen */
  W_FOURTEEN,        /* fourteen */
  W_FIFTEEN,         /* fifteen */
  W_SIXTEEN,         /* sixteen */
  W_SEVENTEEN,       /* seventeen */
  W_EIGHTEEN,        /* eighteen */
  W_NINETEEN,        /* nineteen */
  W_TWENTY,          /* twenty */
  W_TWENTYDASH,      /* twenty- */
  W_QUARTER,         /* quarter */
  W_HALF,            /* half */
  W_PAST,            /* past */
  W_TO,              /* to */
  W_MIDNIGHT,        /* midnight */
  W_MIDDAY,          /* midday */
  W_NOON,            /* noon */
  W_THE,             /* the */
  W_WITCHING,        /* witching */
  W_HOUR,            /* hour */
  W_OCLOCK,          /* o'|clock */
  W_MINUTE,          /* minute */
  W_MINUTES,         /* minutes */
  W_SOLO_MIDNIGHT,   /* midnight */
  W_SOLO_MIDDAY,     /* midday */
  W_D0,              /* 0 */
  W_D1,              /* 1 */
  W_D2,              /* 2 */
  W_D3,              /* 3 */
  W_D4,              /* 4 */
  W_D5,              /* 5 */
  W_D6,              /* 6 */
  W_D7,              /* 7 */
  W_D8,              /* 8 */
  W_D9,              /* 9 */
  W_MON1,            /* Jan. */
  W_MON2,            /* Feb. */
  W_MON3,            /* Mar. */
  W_MON4,            /* Apr. */
  W_MON5,            /* May */
  W_MON6,            /* Jun. */
  W_MON7,            /* Jul. */
  W_MON8,            /* Aug. */
  W_MON9,            /* Sep. */
  W_MON10,           /* Oct. */
  W_MON11,           /* Nov. */
  W_MON12,           /* Dec. */
  W_ST,              /* st */
  W_ND,              /* nd */
  W_RD,              /* rd */
  W_TH,              /* th */
  W_COUNT
} WordId;

static const WordGeom WORDS[W_COUNT] = {
  {RESOURCE_ID_W_ONE, 47, 16, 16},
  {RESOURCE_ID_W_TWO, 50, 23, 23},
  {RESOURCE_ID_W_THREE, 75, 30, 29},
  {RESOURCE_ID_W_FOUR, 59, 42, 31},
  {RESOURCE_ID_W_FIVE, 55, 42, 31},
  {RESOURCE_ID_W_SIX, 41, 22, 21},
  {RESOURCE_ID_W_SEVEN, 77, 16, 16},
  {RESOURCE_ID_W_EIGHT, 74, 45, 29},
  {RESOURCE_ID_W_NINE, 63, 21, 21},
  {RESOURCE_ID_W_TEN, 46, 23, 23},
  {RESOURCE_ID_W_ELEVEN, 90, 32, 31},
  {RESOURCE_ID_W_TWELVE, 93, 32, 31},
  {RESOURCE_ID_W_THIRTEEN, 117, 30, 29},
  {RESOURCE_ID_W_FOURTEEN, 120, 42, 31},
  {RESOURCE_ID_W_FIFTEEN, 100, 42, 31},
  {RESOURCE_ID_W_SIXTEEN, 103, 24, 23},
  {RESOURCE_ID_W_SEVENTEEN, 139, 23, 23},
  {RESOURCE_ID_W_EIGHTEEN, 123, 45, 29},
  {RESOURCE_ID_W_NINETEEN, 125, 23, 23},
  {RESOURCE_ID_W_TWENTY, 101, 38, 23},
  {RESOURCE_ID_W_TWENTYDASH, 110, 38, 23},
  {RESOURCE_ID_W_QUARTER, 110, 37, 23},
  {RESOURCE_ID_W_HALF, 67, 42, 31},
  {RESOURCE_ID_W_PAST, 68, 37, 23},
  {RESOURCE_ID_W_TO, 26, 23, 23},
  {RESOURCE_ID_W_MIDNIGHT, 139, 46, 30},
  {RESOURCE_ID_W_MIDDAY, 120, 45, 30},
  {RESOURCE_ID_W_NOON, 63, 16, 16},
  {RESOURCE_ID_W_THE, 46, 30, 29},
  {RESOURCE_ID_W_WITCHING, 127, 45, 29},
  {RESOURCE_ID_W_HOUR, 62, 30, 29},
  {RESOURCE_ID_W_OCLOCK, 98, 32, 31},
  {RESOURCE_ID_W_MINUTE, 65, 15, 15},
  {RESOURCE_ID_W_MINUTES, 73, 15, 15},
  {RESOURCE_ID_W_SOLO_MIDNIGHT, 160, 52, 34},
  {RESOURCE_ID_W_SOLO_MIDDAY, 138, 51, 34},
  {RESOURCE_ID_W_D0, 11, 12, 12},
  {RESOURCE_ID_W_D1, 6, 12, 12},
  {RESOURCE_ID_W_D2, 12, 12, 12},
  {RESOURCE_ID_W_D3, 10, 12, 12},
  {RESOURCE_ID_W_D4, 10, 12, 12},
  {RESOURCE_ID_W_D5, 11, 12, 12},
  {RESOURCE_ID_W_D6, 10, 12, 12},
  {RESOURCE_ID_W_D7, 9, 12, 12},
  {RESOURCE_ID_W_D8, 11, 12, 12},
  {RESOURCE_ID_W_D9, 10, 12, 12},
  {RESOURCE_ID_W_MON1, 43, 23, 15},
  {RESOURCE_ID_W_MON2, 37, 20, 17},
  {RESOURCE_ID_W_MON3, 39, 19, 15},
  {RESOURCE_ID_W_MON4, 41, 25, 17},
  {RESOURCE_ID_W_MON5, 41, 24, 15},
  {RESOURCE_ID_W_MON6, 43, 23, 15},
  {RESOURCE_ID_W_MON7, 38, 27, 19},
  {RESOURCE_ID_W_MON8, 44, 26, 17},
  {RESOURCE_ID_W_MON9, 39, 23, 15},
  {RESOURCE_ID_W_MON10, 34, 16, 16},
  {RESOURCE_ID_W_MON11, 34, 17, 16},
  {RESOURCE_ID_W_MON12, 36, 16, 16},
  {RESOURCE_ID_W_ST, 10, 9, 9},
  {RESOURCE_ID_W_ND, 16, 11, 11},
  {RESOURCE_ID_W_RD, 15, 11, 11},
  {RESOURCE_ID_W_TH, 11, 11, 11},
};
