/* GENERATED by tools/tune.py - do not edit. */
/* Canvas HEIGHT and BASELINE are uniform within a size family, so */
/* swapping one word for another moves nothing around it. Widths   */
/* stay tight to each word's own ink. */

#pragma once
#include <stdint.h>

/* Marks a geometry.h new enough to contain the weekday words.
   handwritten.c #errors without it, so a stale file cannot be
   built against silently - the same trick as TIME_BOX_H. */
#define GEOMETRY_HAS_WEEKDAYS 1

/* Marks a geometry.h that carries BOTH typefaces. Same guard
   trick again: a stale file would compile with one table where
   the watchface expects two, and index off the end of it. */
#define GEOMETRY_HAS_TYPEFACES 1
#define TYPEFACE_COUNT 2

/* Family boxes: ascent + descent, and the shared baseline offset. */
#define TIME_BOX_H 51
#define TIME_BOX_BASE 34
#define SOLO_BOX_H 58
#define SOLO_BOX_BASE 39
#define MINS_BOX_H 16
#define MINS_BOX_BASE 16
#define DATE_BOX_H 28
#define DATE_BOX_BASE 19
#define ORD_BOX_H 11
#define ORD_BOX_BASE 11
#define HEDGE_BOX_H 32
#define HEDGE_BOX_BASE 21

/* Ink ascent of "twenty-", the top row of the tallest phrase. The
   difference from TIME_BOX_BASE is the only slack at the top of the
   screen, so config.h's budget assertion needs it. */
#define SPLIT_HEAD_ASC 26

typedef struct {
  uint32_t res;   /* resource id            */
  uint8_t w, h;   /* canvas size in pixels  */
  uint8_t base;   /* canvas top -> baseline */
} WordGeom;

typedef enum {
  W_ONE,             /* one */
  W_TWO,             /* two */
  W_THREE,           /* three */
  W_FOUR,            /* four */
  W_FIVE,            /* five */
  W_SIX,             /* six */
  W_SEVEN,           /* seven */
  W_EIGHT,           /* eight */
  W_NINE,            /* nine */
  W_TEN,             /* ten */
  W_ELEVEN,          /* eleven */
  W_TWELVE,          /* twelve */
  W_THIRTEEN,        /* thirteen */
  W_FOURTEEN,        /* fourteen */
  W_FIFTEEN,         /* fifteen */
  W_SIXTEEN,         /* sixteen */
  W_SEVENTEEN,       /* seventeen */
  W_EIGHTEEN,        /* eighteen */
  W_NINETEEN,        /* nineteen */
  W_TWENTY,          /* twenty */
  W_TWENTYDASH,      /* twenty- */
  W_QUARTER,         /* quarter */
  W_HALF,            /* half */
  W_PAST,            /* past */
  W_TO,              /* to */
  W_MIDNIGHT,        /* midnight */
  W_MIDDAY,          /* midday */
  W_NOON,            /* noon */
  W_MINUTE,          /* minute */
  W_MINUTES,         /* minutes */
  W_SOLO_MIDNIGHT,   /* midnight */
  W_SOLO_MIDDAY,     /* midday */
  W_D0,              /* 0 */
  W_D1,              /* 1 */
  W_D2,              /* 2 */
  W_D3,              /* 3 */
  W_D4,              /* 4 */
  W_D5,              /* 5 */
  W_D6,              /* 6 */
  W_D7,              /* 7 */
  W_D8,              /* 8 */
  W_D9,              /* 9 */
  W_MON1,            /* Jan. */
  W_MON2,            /* Feb. */
  W_MON3,            /* Mar. */
  W_MON4,            /* Apr. */
  W_MON5,            /* May */
  W_MON6,            /* Jun. */
  W_MON7,            /* Jul. */
  W_MON8,            /* Aug. */
  W_MON9,            /* Sep. */
  W_MON10,           /* Oct. */
  W_MON11,           /* Nov. */
  W_MON12,           /* Dec. */
  W_ST,              /* st */
  W_ND,              /* nd */
  W_RD,              /* rd */
  W_TH,              /* th */
  W_DOW_SUN,         /* Sun. */
  W_DOW_MON,         /* Mon. */
  W_DOW_TUE,         /* Tue. */
  W_DOW_WED,         /* Wed. */
  W_DOW_THU,         /* Thu. */
  W_DOW_FRI,         /* Fri. */
  W_DOW_SAT,         /* Sat. */
  W_SOLO_ONE,        /* one */
  W_SOLO_TWO,        /* two */
  W_SOLO_THREE,      /* three */
  W_SOLO_FOUR,       /* four */
  W_SOLO_FIVE,       /* five */
  W_SOLO_SIX,        /* six */
  W_SOLO_SEVEN,      /* seven */
  W_SOLO_EIGHT,      /* eight */
  W_SOLO_NINE,       /* nine */
  W_SOLO_TEN,        /* ten */
  W_SOLO_ELEVEN,     /* eleven */
  W_SOLO_OCLOCK,     /* o'|clock */
  W_SOLO_THE,        /* the */
  W_SOLO_WITCHING,   /* witching */
  W_SOLO_HOUR,       /* hour */
  W_TWENTYFIVE,      /* twenty-five */
  W_JUST_GONE,       /* just|gone */
  W_NEARLY,          /* nearly */
  W_COUNT
} WordId;

/* [0] the font, [1] the handwriting. A word nobody has drawn yet
   repeats its font row, so the two typefaces can be swapped at any
   time and an undrawn word simply does not change. Nothing in the
   watchface has to know which words exist in which typeface. */
static const WordGeom WORDS[TYPEFACE_COUNT][W_COUNT] = {
  {
    {RESOURCE_ID_W_ONE, 52, 51, 34},
    {RESOURCE_ID_W_TWO, 55, 51, 34},
    {RESOURCE_ID_W_THREE, 83, 51, 34},
    {RESOURCE_ID_W_FOUR, 64, 51, 34},
    {RESOURCE_ID_W_FIVE, 60, 51, 34},
    {RESOURCE_ID_W_SIX, 45, 51, 34},
    {RESOURCE_ID_W_SEVEN, 85, 51, 34},
    {RESOURCE_ID_W_EIGHT, 82, 51, 34},
    {RESOURCE_ID_W_NINE, 69, 51, 34},
    {RESOURCE_ID_W_TEN, 51, 51, 34},
    {RESOURCE_ID_W_ELEVEN, 99, 51, 34},
    {RESOURCE_ID_W_TWELVE, 103, 51, 34},
    {RESOURCE_ID_W_THIRTEEN, 129, 51, 34},
    {RESOURCE_ID_W_FOURTEEN, 132, 51, 34},
    {RESOURCE_ID_W_FIFTEEN, 110, 51, 34},
    {RESOURCE_ID_W_SIXTEEN, 114, 51, 34},
    {RESOURCE_ID_W_SEVENTEEN, 153, 51, 34},
    {RESOURCE_ID_W_EIGHTEEN, 135, 51, 34},
    {RESOURCE_ID_W_NINETEEN, 137, 51, 34},
    {RESOURCE_ID_W_TWENTY, 111, 51, 34},
    {RESOURCE_ID_W_TWENTYDASH, 122, 51, 34},
    {RESOURCE_ID_W_QUARTER, 121, 51, 34},
    {RESOURCE_ID_W_HALF, 73, 51, 34},
    {RESOURCE_ID_W_PAST, 74, 51, 34},
    {RESOURCE_ID_W_TO, 29, 51, 34},
    {RESOURCE_ID_W_MIDNIGHT, 154, 51, 34},
    {RESOURCE_ID_W_MIDDAY, 132, 51, 34},
    {RESOURCE_ID_W_NOON, 69, 51, 34},
    {RESOURCE_ID_W_MINUTE, 70, 16, 16},
    {RESOURCE_ID_W_MINUTES, 79, 16, 16},
    {RESOURCE_ID_W_SOLO_MIDNIGHT, 174, 58, 39},
    {RESOURCE_ID_W_SOLO_MIDDAY, 150, 58, 39},
    {RESOURCE_ID_W_D0, 11, 28, 19},
    {RESOURCE_ID_W_D1, 6, 28, 19},
    {RESOURCE_ID_W_D2, 12, 28, 19},
    {RESOURCE_ID_W_D3, 10, 28, 19},
    {RESOURCE_ID_W_D4, 10, 28, 19},
    {RESOURCE_ID_W_D5, 11, 28, 19},
    {RESOURCE_ID_W_D6, 10, 28, 19},
    {RESOURCE_ID_W_D7, 9, 28, 19},
    {RESOURCE_ID_W_D8, 11, 28, 19},
    {RESOURCE_ID_W_D9, 10, 28, 19},
    {RESOURCE_ID_W_MON1, 43, 28, 19},
    {RESOURCE_ID_W_MON2, 37, 28, 19},
    {RESOURCE_ID_W_MON3, 39, 28, 19},
    {RESOURCE_ID_W_MON4, 41, 28, 19},
    {RESOURCE_ID_W_MON5, 41, 28, 19},
    {RESOURCE_ID_W_MON6, 43, 28, 19},
    {RESOURCE_ID_W_MON7, 38, 28, 19},
    {RESOURCE_ID_W_MON8, 44, 28, 19},
    {RESOURCE_ID_W_MON9, 39, 28, 19},
    {RESOURCE_ID_W_MON10, 34, 28, 19},
    {RESOURCE_ID_W_MON11, 34, 28, 19},
    {RESOURCE_ID_W_MON12, 36, 28, 19},
    {RESOURCE_ID_W_ST, 10, 11, 11},
    {RESOURCE_ID_W_ND, 16, 11, 11},
    {RESOURCE_ID_W_RD, 15, 11, 11},
    {RESOURCE_ID_W_TH, 11, 11, 11},
    {RESOURCE_ID_W_DOW_SUN, 40, 28, 19},
    {RESOURCE_ID_W_DOW_MON, 41, 28, 19},
    {RESOURCE_ID_W_DOW_TUE, 31, 28, 19},
    {RESOURCE_ID_W_DOW_WED, 40, 28, 19},
    {RESOURCE_ID_W_DOW_THU, 36, 28, 19},
    {RESOURCE_ID_W_DOW_FRI, 32, 28, 19},
    {RESOURCE_ID_W_DOW_SAT, 37, 28, 19},
    {RESOURCE_ID_W_SOLO_ONE, 59, 58, 39},
    {RESOURCE_ID_W_SOLO_TWO, 63, 58, 39},
    {RESOURCE_ID_W_SOLO_THREE, 94, 58, 39},
    {RESOURCE_ID_W_SOLO_FOUR, 73, 58, 39},
    {RESOURCE_ID_W_SOLO_FIVE, 68, 58, 39},
    {RESOURCE_ID_W_SOLO_SIX, 52, 58, 39},
    {RESOURCE_ID_W_SOLO_SEVEN, 96, 58, 39},
    {RESOURCE_ID_W_SOLO_EIGHT, 93, 58, 39},
    {RESOURCE_ID_W_SOLO_NINE, 79, 58, 39},
    {RESOURCE_ID_W_SOLO_TEN, 58, 58, 39},
    {RESOURCE_ID_W_SOLO_ELEVEN, 112, 58, 39},
    {RESOURCE_ID_W_SOLO_OCLOCK, 122, 58, 39},
    {RESOURCE_ID_W_SOLO_THE, 57, 58, 39},
    {RESOURCE_ID_W_SOLO_WITCHING, 158, 58, 39},
    {RESOURCE_ID_W_SOLO_HOUR, 78, 58, 39},
    {RESOURCE_ID_W_TWENTYFIVE, 181, 51, 34},
    {RESOURCE_ID_W_JUST_GONE, 98, 32, 21},
    {RESOURCE_ID_W_NEARLY, 63, 32, 21},
  },
  {
    {RESOURCE_ID_W_ONE, 52, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_TWO, 55, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_THREE, 83, 51, 34},   /* not drawn */
    {RESOURCE_ID_H_FOUR, 67, 51, 34},
    {RESOURCE_ID_H_FIVE, 57, 51, 34},
    {RESOURCE_ID_W_SIX, 45, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_SEVEN, 85, 51, 34},   /* not drawn */
    {RESOURCE_ID_H_EIGHT, 75, 51, 34},
    {RESOURCE_ID_W_NINE, 69, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_TEN, 51, 51, 34},   /* not drawn */
    {RESOURCE_ID_H_ELEVEN, 94, 51, 34},
    {RESOURCE_ID_W_TWELVE, 103, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_THIRTEEN, 129, 51, 34},   /* not drawn */
    {RESOURCE_ID_H_FOURTEEN, 121, 51, 34},
    {RESOURCE_ID_H_FIFTEEN, 99, 51, 34},
    {RESOURCE_ID_W_SIXTEEN, 114, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_SEVENTEEN, 153, 51, 34},   /* not drawn */
    {RESOURCE_ID_H_EIGHTEEN, 117, 51, 34},
    {RESOURCE_ID_W_NINETEEN, 137, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_TWENTY, 111, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_TWENTYDASH, 122, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_QUARTER, 121, 51, 34},   /* not drawn */
    {RESOURCE_ID_H_HALF, 66, 51, 34},
    {RESOURCE_ID_W_PAST, 74, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_TO, 29, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_MIDNIGHT, 154, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_MIDDAY, 132, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_NOON, 69, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_MINUTE, 70, 16, 16},   /* not drawn */
    {RESOURCE_ID_W_MINUTES, 79, 16, 16},   /* not drawn */
    {RESOURCE_ID_W_SOLO_MIDNIGHT, 174, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_MIDDAY, 150, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_D0, 11, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D1, 6, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D2, 12, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D3, 10, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D4, 10, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D5, 11, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D6, 10, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D7, 9, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D8, 11, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_D9, 10, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON1, 43, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON2, 37, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON3, 39, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON4, 41, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON5, 41, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON6, 43, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON7, 38, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON8, 44, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON9, 39, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON10, 34, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON11, 34, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_MON12, 36, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_ST, 10, 11, 11},   /* not drawn */
    {RESOURCE_ID_W_ND, 16, 11, 11},   /* not drawn */
    {RESOURCE_ID_W_RD, 15, 11, 11},   /* not drawn */
    {RESOURCE_ID_W_TH, 11, 11, 11},   /* not drawn */
    {RESOURCE_ID_W_DOW_SUN, 40, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_DOW_MON, 41, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_DOW_TUE, 31, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_DOW_WED, 40, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_DOW_THU, 36, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_DOW_FRI, 32, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_DOW_SAT, 37, 28, 19},   /* not drawn */
    {RESOURCE_ID_W_SOLO_ONE, 59, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_TWO, 63, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_THREE, 94, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_FOUR, 73, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_FIVE, 68, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_SIX, 52, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_SEVEN, 96, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_EIGHT, 93, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_NINE, 79, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_TEN, 58, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_ELEVEN, 112, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_OCLOCK, 122, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_THE, 57, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_WITCHING, 158, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_SOLO_HOUR, 78, 58, 39},   /* not drawn */
    {RESOURCE_ID_W_TWENTYFIVE, 181, 51, 34},   /* not drawn */
    {RESOURCE_ID_W_JUST_GONE, 98, 32, 21},   /* not drawn */
    {RESOURCE_ID_W_NEARLY, 63, 32, 21},   /* not drawn */
  },
};
