/* GENERATED by tools/tune.py - do not edit. */
/* Canvas HEIGHT and BASELINE are uniform within a size family, so */
/* swapping one word for another moves nothing around it. Widths   */
/* stay tight to each word's own ink. */

#pragma once
#include <stdint.h>

/* Family boxes: ascent + descent, and the shared baseline offset. */
#define TIME_BOX_H 47
#define TIME_BOX_BASE 31
#define SOLO_BOX_H 52
#define SOLO_BOX_BASE 34
#define MINS_BOX_H 15
#define MINS_BOX_BASE 15
#define DATE_BOX_H 28
#define DATE_BOX_BASE 19
#define ORD_BOX_H 11
#define ORD_BOX_BASE 11

/* Ink ascent of "twenty-", the top row of the tallest phrase. The
   difference from TIME_BOX_BASE is the only slack at the top of the
   screen, so config.h's budget assertion needs it. */
#define SPLIT_HEAD_ASC 23

typedef struct {
  uint32_t res;   /* resource id            */
  uint8_t w, h;   /* canvas size in pixels  */
  uint8_t base;   /* canvas top -> baseline */
} WordGeom;

typedef enum {
  W_ONE,             /* one */
  W_TWO,             /* two */
  W_THREE,           /* three */
  W_FOUR,            /* four */
  W_FIVE,            /* five */
  W_SIX,             /* six */
  W_SEVEN,           /* seven */
  W_EIGHT,           /* eight */
  W_NINE,            /* nine */
  W_TEN,             /* ten */
  W_ELEVEN,          /* eleven */
  W_TWELVE,          /* twelve */
  W_THIRTEEN,        /* thirteen */
  W_FOURTEEN,        /* fourteen */
  W_FIFTEEN,         /* fifteen */
  W_SIXTEEN,         /* sixteen */
  W_SEVENTEEN,       /* seventeen */
  W_EIGHTEEN,        /* eighteen */
  W_NINETEEN,        /* nineteen */
  W_TWENTY,          /* twenty */
  W_TWENTYDASH,      /* twenty- */
  W_QUARTER,         /* quarter */
  W_HALF,            /* half */
  W_PAST,            /* past */
  W_TO,              /* to */
  W_MIDNIGHT,        /* midnight */
  W_MIDDAY,          /* midday */
  W_NOON,            /* noon */
  W_THE,             /* the */
  W_WITCHING,        /* witching */
  W_HOUR,            /* hour */
  W_OCLOCK,          /* o'|clock */
  W_MINUTE,          /* minute */
  W_MINUTES,         /* minutes */
  W_SOLO_MIDNIGHT,   /* midnight */
  W_SOLO_MIDDAY,     /* midday */
  W_D0,              /* 0 */
  W_D1,              /* 1 */
  W_D2,              /* 2 */
  W_D3,              /* 3 */
  W_D4,              /* 4 */
  W_D5,              /* 5 */
  W_D6,              /* 6 */
  W_D7,              /* 7 */
  W_D8,              /* 8 */
  W_D9,              /* 9 */
  W_MON1,            /* Jan. */
  W_MON2,            /* Feb. */
  W_MON3,            /* Mar. */
  W_MON4,            /* Apr. */
  W_MON5,            /* May */
  W_MON6,            /* Jun. */
  W_MON7,            /* Jul. */
  W_MON8,            /* Aug. */
  W_MON9,            /* Sep. */
  W_MON10,           /* Oct. */
  W_MON11,           /* Nov. */
  W_MON12,           /* Dec. */
  W_ST,              /* st */
  W_ND,              /* nd */
  W_RD,              /* rd */
  W_TH,              /* th */
  W_COUNT
} WordId;

static const WordGeom WORDS[W_COUNT] = {
  {RESOURCE_ID_W_ONE, 47, 47, 31},
  {RESOURCE_ID_W_TWO, 50, 47, 31},
  {RESOURCE_ID_W_THREE, 75, 47, 31},
  {RESOURCE_ID_W_FOUR, 59, 47, 31},
  {RESOURCE_ID_W_FIVE, 55, 47, 31},
  {RESOURCE_ID_W_SIX, 41, 47, 31},
  {RESOURCE_ID_W_SEVEN, 77, 47, 31},
  {RESOURCE_ID_W_EIGHT, 74, 47, 31},
  {RESOURCE_ID_W_NINE, 63, 47, 31},
  {RESOURCE_ID_W_TEN, 46, 47, 31},
  {RESOURCE_ID_W_ELEVEN, 90, 47, 31},
  {RESOURCE_ID_W_TWELVE, 93, 47, 31},
  {RESOURCE_ID_W_THIRTEEN, 117, 47, 31},
  {RESOURCE_ID_W_FOURTEEN, 120, 47, 31},
  {RESOURCE_ID_W_FIFTEEN, 100, 47, 31},
  {RESOURCE_ID_W_SIXTEEN, 103, 47, 31},
  {RESOURCE_ID_W_SEVENTEEN, 139, 47, 31},
  {RESOURCE_ID_W_EIGHTEEN, 123, 47, 31},
  {RESOURCE_ID_W_NINETEEN, 125, 47, 31},
  {RESOURCE_ID_W_TWENTY, 101, 47, 31},
  {RESOURCE_ID_W_TWENTYDASH, 110, 47, 31},
  {RESOURCE_ID_W_QUARTER, 110, 47, 31},
  {RESOURCE_ID_W_HALF, 67, 47, 31},
  {RESOURCE_ID_W_PAST, 68, 47, 31},
  {RESOURCE_ID_W_TO, 26, 47, 31},
  {RESOURCE_ID_W_MIDNIGHT, 139, 47, 31},
  {RESOURCE_ID_W_MIDDAY, 120, 47, 31},
  {RESOURCE_ID_W_NOON, 63, 47, 31},
  {RESOURCE_ID_W_THE, 46, 47, 31},
  {RESOURCE_ID_W_WITCHING, 127, 47, 31},
  {RESOURCE_ID_W_HOUR, 62, 47, 31},
  {RESOURCE_ID_W_OCLOCK, 98, 47, 31},
  {RESOURCE_ID_W_MINUTE, 65, 15, 15},
  {RESOURCE_ID_W_MINUTES, 73, 15, 15},
  {RESOURCE_ID_W_SOLO_MIDNIGHT, 160, 52, 34},
  {RESOURCE_ID_W_SOLO_MIDDAY, 138, 52, 34},
  {RESOURCE_ID_W_D0, 11, 28, 19},
  {RESOURCE_ID_W_D1, 6, 28, 19},
  {RESOURCE_ID_W_D2, 12, 28, 19},
  {RESOURCE_ID_W_D3, 10, 28, 19},
  {RESOURCE_ID_W_D4, 10, 28, 19},
  {RESOURCE_ID_W_D5, 11, 28, 19},
  {RESOURCE_ID_W_D6, 10, 28, 19},
  {RESOURCE_ID_W_D7, 9, 28, 19},
  {RESOURCE_ID_W_D8, 11, 28, 19},
  {RESOURCE_ID_W_D9, 10, 28, 19},
  {RESOURCE_ID_W_MON1, 43, 28, 19},
  {RESOURCE_ID_W_MON2, 37, 28, 19},
  {RESOURCE_ID_W_MON3, 39, 28, 19},
  {RESOURCE_ID_W_MON4, 41, 28, 19},
  {RESOURCE_ID_W_MON5, 41, 28, 19},
  {RESOURCE_ID_W_MON6, 43, 28, 19},
  {RESOURCE_ID_W_MON7, 38, 28, 19},
  {RESOURCE_ID_W_MON8, 44, 28, 19},
  {RESOURCE_ID_W_MON9, 39, 28, 19},
  {RESOURCE_ID_W_MON10, 34, 28, 19},
  {RESOURCE_ID_W_MON11, 34, 28, 19},
  {RESOURCE_ID_W_MON12, 36, 28, 19},
  {RESOURCE_ID_W_ST, 10, 11, 11},
  {RESOURCE_ID_W_ND, 16, 11, 11},
  {RESOURCE_ID_W_RD, 15, 11, 11},
  {RESOURCE_ID_W_TH, 11, 11, 11},
};
